# License: This file is part of TrailCatch.
# Copyright (c) 2024 Ihar Petushkou.
#
# This source code is for personal or educational use only.
# Commercial use, redistribution, or modification is prohibited
# without explicit permission. See LICENSE for details.

name: trailcatch
description: TrailCatch
publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  provider: ^6.1.2
  get_it: ^8.0.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  encrypted_shared_preferences: ^3.0.1
  flutter_secure_storage: ^9.2.2
  collection: ^1.18.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.1
  app_badge_plus: ^1.1.5
  csv: ^6.0.0
  in_app_purchase: ^3.2.0
  app_tracking_transparency: ^2.0.6
  package_info_plus: ^8.1.0
  app_links: ^6.3.2
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  convert: ^3.1.2
  crypto: ^3.0.6
  path_provider: ^2.1.4
  sign_in_with_apple: ^6.1.3
  google_sign_in: ^6.2.1
  eraser: ^3.0.0
  qonversion_flutter: ^9.1.5
  ios_open_subscriptions_settings: ^0.0.4
  dio: ^5.7.0
  logger: ^2.4.0
  safe_text: ^1.0.7
  fc_native_image_resize: ^0.12.0
  nsfw_detector_flutter: ^1.0.4
  local_auth: ^2.3.0
  loading_indicator: ^3.1.1
  geo_sort: ^0.1.0
  geodesy: ^0.10.2
  file_picker: ^8.1.3
  qr_flutter: ^4.1.0
  sentry_flutter: ^8.9.0
  app_settings: ^5.1.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  build_runner: ^2.4.13

flutter_launcher_icons:
  image_path: 'assets/***/app_icon.png' 
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: '#161415'
  ios: true
  fullscreen: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/***/
    - assets/***/
    - assets/***/
  fonts:
    - family: 'Ubuntu Regular'
      fonts:
        - asset: 'assets/***/Ubuntu/Ubuntu-Regular.ttf'
    - family: 'Ubuntu Light'
      fonts:
        - asset: 'assets/***/Ubuntu/Ubuntu-Light.ttf'